interface {
	CloneCampaign(*URL, Header) (int, Header, *Campaign, error)
	CohortsQuery(*URL, Header) (int, Header, []string, error)
	CohortsQueryColumns(*URL, Header) (int, Header, []string, error)
	CreateCampaign(*URL, Header, *Campaign) (int, Header, *Campaign, error)
	CreateOffer(*URL, Header, *Offer) (int, Header, *Offer, error)
	CreatePromotion(*URL, Header, *Promotion) (int, Header, *Promotion, error)
	CreateSegment(*URL, Header, *Segment) (int, Header, *Segment, error)
	CreateTemplate(*URL, Header, *Template) (int, Header, *Template, error)
	DeleteSegment(*URL, Header) (int, Header, *Segment, error)
	FundPromotion(*URL, Header, *Amount) (int, Header, *Balance, error)
	GetAccountCreditLedgers(*URL, Header) (int, Header, []*Ledger, error)
	GetBrands(*URL, Header) (int, Header, []*Brand, error)
	GetCampaign(*URL, Header) (int, Header, *Campaign, error)
	GetCampaignStats(*URL, Header) (int, Header, *CampaignStats, error)
	GetCampaigns(*URL, Header) (int, Header, []*Campaign, error)
	GetHealth(*URL, Header) (int, Header, *Health, error)
	GetIdentities(*URL, Header) (int, Header, []*Identity, error)
	GetOffer(*URL, Header) (int, Header, *Offer, error)
	GetOffers(*URL, Header) (int, Header, []*Offer, error)
	GetOrganizations(*URL, Header) (int, Header, []*Organization, error)
	// slide break 1 OMIT
	GetPromotion(*URL, Header) (int, Header, *Promotion, error)
	GetPromotions(*URL, Header) (int, Header, []*Promotion, error)
	GetTemplate(*URL, Header) (int, Header, *Template, error)
	GetTemplateAssetURL(*URL, Header) (int, Header, string, error)
	GetTemplates(*URL, Header) (int, Header, []*Template, error)
	GetUserDetails(*URL, Header) (int, Header, *UserVariables, error)
	ListSegments(*URL, Header) (int, Header, []*Segment, error)
	NetEntFreeSpinsGames(*URL, Header) (int, Header, map[string]string, error)
	NetEntFreeSpinsLedgers(*URL, Header) (int, Header, map[string]string, error)
	OptimoveActions(*URL, Header) (int, Header, []*Action, error)
	OptimoveTargetGroupActions(*URL, Header) (int, Header, []*Action, error)
	OptimoveTargetGroups(*URL, Header) (int, Header, []*TargetGroup, error)
	PauseCampaign(*URL, Header) (int, Header, interface{}, error)
	PostUploadTest(*URL, Header, *Campaign) (int, Header, *Campaign, error)
	PreflightCampaign(*URL, Header, *PreflightArg) (int, Header, []*Message, error)
	PushNotifClients(*URL, Header) (int, Header, *PNClients, error)
	PushNotifKinds(*URL, Header) (int, Header, *PNKinds, error)
	QuerySegment(*URL, Header) (int, Header, []string, error)
	QuerySegmentColumns(*URL, Header) (int, Header, [][]string, error)
	RawQuery(*URL, Header) (int, Header, []string, error)
	RawQueryColumns(*URL, Header) (int, Header, []string, error)
	// slide break 2 OMIT
	ReadSegment(*URL, Header) (int, Header, *Segment, error)
	ResumeCampaign(*URL, Header) (int, Header, interface{}, error)
	ScheduleCampaign(*URL, Header, *Schedule) (int, Header, []*Message, error)
	SendPushNotif(*URL, Header, *PushNotif) (int, Header, interface{}, error)
	SignOffer(u *URL, h Header) (int, Header, *URL, error)
	StopCampaign(*URL, Header) (int, Header, interface{}, error)
	SyncIdentities(*URL, Header) (int, Header, []*Identity, error)
	SyncTemplates(*URL, Header) (int, Header, []*Template, error)
	UpdateCampaign(*URL, Header, *Campaign) (int, Header, *Campaign, error)
	UpdateSegment(*URL, Header, *Segment) (int, Header, *Segment, error)
	UpdateOffer(*URL, Header, *Offer) (int, Header, *Offer, error)
	UpdatePromotion(*URL, Header, *Promotion) (int, Header, *Promotion, error)
	UpdateTemplate(*URL, Header, *Template) (int, Header, *Template, error)
}
